// Export all services from a single entry point
export * from "./api.service";
export * from "./auth.service";
export * from "./amenities.service";
export { unitTypeService } from "./unitTypeService";
export { locationService } from "./locationService";
export { locationTypeService } from "./locationTypeService";
export { addonTypeService } from "./addonTypeService";
export { addonService } from "./addonService";
export { addonItemService } from "./addonItemService";
export { unitAddonService } from "./unitAddonService";
export { unitResidentService } from "./unitResidentService";
export { invitationService } from "./invitationService";
export { unitMemberService } from "./unitMemberService";
export { inviteOrLinkResident } from "./residentInviteFlow";
export type { InviteOrLinkOutcome } from "./residentInviteFlow";
export { unitRentalService } from "./unitRentalService";
export { unitRentalPaymentService } from "./unitRentalPaymentService";
export { chargeService } from "./chargeService";
export { billingService, monthToPeriod } from "./billingService";
export { chargeAssignmentService } from "./chargeAssignmentService";
export { auditLogService } from "./auditLogService";
export { vehicleService } from "./vehicleService";
export { visitorService } from "./visitorService";
export { accessLogService } from "./accessLogService";
export { incidentService } from "./incidentService";
export { incidentAttachmentService } from "./incidentAttachmentService";
export { incidentTypeService } from "./incidentTypeService";
export { amenityBookingService } from "./amenityBookingService";
export { dashboardMetricsService } from "./dashboardMetricsService";
export { inboxService } from "./inboxService";
export type { AdminAlert, AdminAlertPayment, PendingCounts, PendingPayment, PendingReservation } from "./inboxService";
export { pushNotificationService } from "./pushNotificationService";
export { bulletinService } from "./bulletinService";
export { bulletinAttachmentService } from "./bulletinAttachmentService";
export { servicesService } from "./services.service";
export { amenityServiceService } from "./amenityServiceService";
export { amenityBookingLimitService } from "./amenityBookingLimitService";
export { amenityBlackoutService } from "./amenityBlackoutService";
export { amenityImageService } from "./amenityImageService";
export type { OperationalMetrics } from "./dashboardMetricsService";
export { platformPlanService } from "./platformPlanService";
export { appSettingsService } from "./appSettingsService";
export type { AppPlatform, PushAudience, MassPushInput, MassPushResult } from "./appSettingsService";
export { providerService } from "./providerService";
export { platformMetricsService } from "./platformMetricsService";
export type { PlatformMetrics } from "./platformMetricsService";

// Re-export commonly used types
export type { TablesUpdate, TablesInsert } from "../types/database.types";
export { guardService } from "./guardService";
export type { CreatedGuard, GuardSignInError } from "./guardService";
export { platformResidentialService, RESIDENTIAL_CODE_RE } from "./platformResidentialService";
export type { CreateResidentialParams } from "./platformResidentialService";
