// Export all services from a single entry point
export * from "./api.service";
export * from "./auth.service";
export * from "./amenities.service";
export { unitTypeService } from "./unitTypeService";
export { locationService } from "./locationService";
export { locationTypeService } from "./locationTypeService";
export { addonTypeService } from "./addonTypeService";
export { addonService } from "./addonService";
export { addonItemService } from "./addonItemService";
export { unitAddonService } from "./unitAddonService";
export { unitResidentService } from "./unitResidentService";
export { invitationService } from "./invitationService";
export { unitMemberService } from "./unitMemberService";
export { inviteOrLinkResident } from "./residentInviteFlow";
export type { InviteOrLinkOutcome } from "./residentInviteFlow";
export { unitRentalService } from "./unitRentalService";
export { unitRentalPaymentService } from "./unitRentalPaymentService";
export { chargeService } from "./chargeService";
export { unitChargeService } from "./unitChargeService";
export { auditLogService } from "./auditLogService";
export { vehicleService } from "./vehicleService";
export { visitorService } from "./visitorService";
export { accessLogService } from "./accessLogService";
export { incidentService } from "./incidentService";
export { incidentAttachmentService } from "./incidentAttachmentService";
export { incidentTypeService } from "./incidentTypeService";
export { amenityBookingService } from "./amenityBookingService";
export { dashboardMetricsService } from "./dashboardMetricsService";
export { announcementService } from "./announcementService";
export { servicesService } from "./services.service";
export { amenityServiceService } from "./amenityServiceService";
export { amenityBookingLimitService } from "./amenityBookingLimitService";
export { amenityImageService } from "./amenityImageService";
export type { OperationalMetrics } from "./dashboardMetricsService";
export { platformPlanService } from "./platformPlanService";
export { providerService } from "./providerService";
export { platformMetricsService } from "./platformMetricsService";
export type { PlatformMetrics } from "./platformMetricsService";

// Re-export commonly used types
export type { TablesUpdate, TablesInsert } from "../types/database.types";
