// Branded transactional email layout (Vecinoo). Single source of truth for:
//  - the Supabase Auth templates (generated by scripts/build-email-templates.mjs
//    into supabase/templates/*.html — don't edit those by hand), and
//  - the invitation email sent by the send-invitation edge function.
// Table-based with inline styles on purpose: Gmail/Outlook/Apple Mail ignore
// most modern CSS. Palette mirrors src/index.css and the landing page.

const INK = "#252d29";
const MUTED = "#68726b";
const BRAND = "#344f40";
const CANVAS = "#f7f8f4";
const SUBTLE = "#eef2eb";
const ACCENT = "#dde8d6";
const LINE = "#dce2da";
const FONT = "Manrope,-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif";

export interface EmailContent {
  /** Hidden inbox-preview text. */
  preheader: string;
  title: string;
  /** Paragraph(s) above the code. Trusted HTML. */
  intro: string;
  /** Code or token to highlight. Pass a Go-template placeholder for Supabase. */
  code: string;
  /** Small label above the code. */
  codeLabel: string;
  /** Paragraph(s) below the code. Trusted HTML. */
  outro: string;
}

// Official app icon (two interlocking rings), served from the landing site
// (vecinoo-landing/images/email-logo.png). Must be a public https URL: Gmail and
// Outlook block data: URIs and inline SVG.
const LOGO_URL = "https://vecinoo.app/images/email-logo.png";
const logoMark = `<img src="${LOGO_URL}" width="44" height="44" alt="" style="display:inline-block;vertical-align:middle;width:44px;height:44px;border:0;border-radius:12px;">`;

export function renderEmail(c: EmailContent): string {
  return `<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light">
<meta name="supported-color-schemes" content="light">
<title>${c.title}</title>
</head>
<body style="margin:0;padding:0;background:${CANVAS};">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;mso-hide:all;">${c.preheader}&#8199;&#847;&#8199;&#847;&#8199;&#847;&#8199;&#847;</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${CANVAS};">
  <tr>
    <td align="center" style="padding:32px 16px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:520px;background:#ffffff;border:1px solid ${LINE};border-radius:20px;overflow:hidden;">
        <tr>
          <td style="background:#ffffff;padding:28px 32px 0;">
            ${logoMark}
            <span style="display:inline-block;vertical-align:middle;margin-left:12px;font-family:${FONT};font-size:28px;font-weight:600;letter-spacing:-0.03em;color:${BRAND};">vecinoo</span>
          </td>
        </tr>
        <tr>
          <td style="padding:36px 32px 8px;font-family:${FONT};color:${INK};">
            <h1 style="margin:0 0 12px;font-family:${FONT};font-size:24px;line-height:1.25;font-weight:700;letter-spacing:-0.4px;color:${INK};">${c.title}</h1>
            <div style="font-size:16px;line-height:1.6;color:${MUTED};">${c.intro}</div>
          </td>
        </tr>
        <tr>
          <td style="padding:20px 32px;">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${SUBTLE};border:1px solid ${ACCENT};border-radius:16px;">
              <tr>
                <td align="center" style="padding:24px 16px;">
                  <div style="font-family:${FONT};font-size:12px;font-weight:600;letter-spacing:1.5px;text-transform:uppercase;color:${MUTED};">${c.codeLabel}</div>
                  <div style="margin-top:10px;font-family:'SF Mono',Menlo,Consolas,'Courier New',monospace;font-size:38px;line-height:1.1;font-weight:700;letter-spacing:10px;color:${BRAND};">${c.code}</div>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td style="padding:0 32px 36px;font-family:${FONT};font-size:14px;line-height:1.6;color:${MUTED};">${c.outro}</td>
        </tr>
        <tr>
          <td style="padding:20px 32px;border-top:1px solid ${LINE};background:${CANVAS};font-family:${FONT};font-size:12px;line-height:1.5;color:${MUTED};">
            Vecinoo &middot; La app de tu residencial.<br>
            Si no esperabas este correo, puedes ignorarlo con seguridad.
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>
`;
}

export function invitationEmail(code: string): string {
  return renderEmail({
    preheader: "Te invitaron a unirte a tu residencial en Vecinoo.",
    title: "Te invitaron a tu residencial",
    intro:
      "<p style=\"margin:0 0 12px;\">Tu administración te invitó a unirte a <strong style=\"color:#252d29;\">Vecinoo</strong>. " +
      "Descarga la app y, al registrarte, ingresa este código de invitación.</p>",
    codeLabel: "Tu código de invitación",
    code,
    outro: "<p style=\"margin:0;\">Este código vence en 24 horas y solo puede usarse una vez.</p>",
  });
}
